### PR TITLE
Check capacity

### PR DESCRIPTION
**Pull request by Djontleman**
Throw error if adding citizen to building at max capacity
Throw error if reducing capacity of building violates citizen count

### CODE REVIEW

**Comment by mechanin** [comment]
wiw

**Comment by mechanin** [comment]
wow

**Comment by vinhchugg** [comment]
This looks good, glad I could help. :)

**Comment by mechanin** [comment]
Looks really good thanks for props

**Comment by vinhchugg** [comment]
Feel free to push when you're ready

**Comment by laiba9999** [comment]
Looks good! Well done Jonathan :D

**Pull request merged**
